### ISSUE TITLE
"How to" for creating issues

### ISSUE THREAD

**Issue by sventhebarbarian** [voteflux/flux-docs#11]
On [https://docs.flux.party/en/latest/docs/contributing/index.html](url) it states a good path before making changes is to create an issue, but it does not explain what this means, how to do it. I would suggest a separate page with instructions how to. 

(I think we should present information with the assumption the reader has no knowledge of Git or any other processes we are using)

**Comment by XertroV** [comment]
We should find some good resources to link Ppl to. I don't know of any off the top of my head tho

**Comment by sventhebarbarian** [comment]
I think we can write up a quick set of instructions for our specific repo, am working with Paul on this

**Comment by XertroV** [comment]
Just be sure to leverage existing material where appropriate

**Comment by pwhipp** [comment]
I've added [this question](https://docs.flux.party/en/latest/docs/faq/general.html) with a link to the github help.
