### ISSUE TITLE
'Shop' or 'Merch' Tab - Add to Flux Website main page

### ISSUE THREAD

**Issue by Alijb68** [voteflux/flux-docs#18]
Please add a 'shop' or 'merch' tab to the main website. It should link to the following with an instruction to 'open in new tab':

https://www.grovewesley.com/store/c33/Flux_Merchandise.html

Thank you in advance, Ali

**Comment by XertroV** [comment]
FYI best to create this sort of issue over on @voteflux/flux-website-v2 - have pushed up a change https://github.com/voteflux/flux-website-v2/commit/b01ef28244240111452db227be7784ddcc11788e
